import { useEffect, useId, useRef, useState } from 'react';
import { useJsonState, imagePreview, previewFile } from '../services/storage';
import { Camera, ImagePlus, X } from 'lucide-react';
export function ImagePicker({ body = false, storageKey = body ? 'profile-photo' : 'meal-photo', onChange }: { body?: boolean; storageKey?:string; onChange?: (file?: File, action?: 'restore' | 'select' | 'remove') => void }) {
 const [url, setUrl] = useJsonState(storageKey,'',value=>typeof value==='string' && (!value || value.startsWith('data:image/'))); const [error, setError] = useState(''); const id = useId(); const camera = useRef<HTMLInputElement>(null); const library = useRef<HTMLInputElement>(null);
 useEffect(() => { if(url){try{const restored=previewFile(url);onChange?.(restored,'restore');}catch{setUrl('');setError('Ảnh lưu chưa đọc được. Hãy chọn ảnh khác.');}} }, []);
 async function choose(next?: File, action: 'select' | 'remove' = 'select') { if (next && (!['image/jpeg','image/png','image/webp'].includes(next.type) || next.size > 5*1024*1024)) { setError('Chọn ảnh JPEG, PNG hoặc WebP tối đa 5 MB. Bạn vẫn có thể nhập bằng văn bản.'); return; } setError(''); if(!next){setUrl('');onChange?.(undefined,'remove');return;}try{const preview=await imagePreview(next);setUrl(preview);onChange?.(next,action);}catch{setError('Không đọc được ảnh. Chọn ảnh khác hoặc nhập bằng văn bản.');} }
 return <div className="image-picker"><input id={`${id}-camera`} hidden ref={camera} type="file" accept="image/jpeg,image/png,image/webp" capture={body ? 'user' : 'environment'} onChange={e => {choose(e.target.files?.[0]); e.target.value='';}}/><input id={`${id}-library`} hidden ref={library} type="file" accept="image/jpeg,image/png,image/webp" onChange={e => {choose(e.target.files?.[0]); e.target.value='';}}/>{url ? <div className="preview"><img src={url} alt={body ? 'Ảnh cơ thể bạn đã chọn' : 'Ảnh bữa ăn bạn đã chọn'} onError={() => {choose(undefined,'remove'); setError('Không đọc được ảnh. Chọn ảnh khác hoặc nhập bằng văn bản.');}}/><button className="icon-button remove-image" type="button" aria-label="Xóa ảnh" onClick={() => choose(undefined,'remove')}><X size={20}/></button></div> : <div className="upload-placeholder"><Camera size={30} strokeWidth={1.5}/><strong>{body ? 'Thêm ảnh cơ thể (tùy chọn)' : 'Tải ảnh bữa ăn lên để ước tính macro'}</strong><span>{body ? 'Không cần khuôn mặt hoặc ảnh nhạy cảm.' : 'AI gợi ý món và khẩu phần; bạn sẽ kiểm tra trước khi ghi.'}</span></div>}<div className="upload-actions">{!body && <button className="secondary" type="button" onClick={() => camera.current?.click()}><Camera size={18}/>Chụp món ăn</button>}<button className="secondary" type="button" onClick={() => library.current?.click()}><ImagePlus size={18}/>{url ? 'Thay ảnh' : 'Chọn từ thư viện'}</button></div><small>{body ? 'Ảnh xem trước được thu nhỏ và lưu trên thiết bị.' : 'Khi bấm “Phân tích ảnh”, ảnh sẽ được gửi tới dịch vụ AI. Ảnh xem trước vẫn lưu trên thiết bị.'} JPEG / PNG / WebP · tối đa 5 MB.</small>{error && <p className="error" role="alert">{error}</p>}</div>;
}
