import { test, expect } from '@playwright/test';
import { createPlan, recalculateMeal } from '../src/services/nutrition';
import { assessMeal } from '../src/services/mealAlignment';
import { foodItem, zero } from '../src/data/foods';
import { demoProfile } from '../src/data/fixtures';
import { answerFoodQuestion } from '../src/services/chat';
import path from 'node:path';

test('Đánh giá theo mục tiêu, khẩu phần và tổng ngày; không khen khi thiếu dữ liệu', async () => {
 const plan = (await createPlan(demoProfile))[0];
 const lean = recalculateMeal([foodItem('chicken',150),foodItem('rice',200),foodItem('vegetable',150)]);
 expect(assessMeal(lean,demoProfile,plan).status).toBe('aligned');
 expect(assessMeal(lean,demoProfile,plan).message).toContain('tăng cơ');
 expect(assessMeal(recalculateMeal([foodItem('chicken',null)]),demoProfile,plan).status).toBe('unknown');
 expect(assessMeal(lean).status).toBe('unknown');
 expect(assessMeal(lean,demoProfile,plan,{...zero(),caloriesKcal:plan.targetMax.caloriesKcal}).status).toBe('review');
 expect(assessMeal(recalculateMeal([foodItem('oil',100)]),demoProfile,plan).status).toBe('review');
 expect(answerFoodQuestion('Ức gà 150 g?',{profile:demoProfile,plan})).toContain('Nếu dùng khẩu phần này');
 const lossProfile = {...demoProfile, goal:'loseFat' as const};
 const lossPlan = (await createPlan(lossProfile))[0];
 expect(assessMeal(lean,lossProfile,lossPlan).status).toBe('aligned');
 expect(assessMeal(recalculateMeal([foodItem('chicken',150)]),lossProfile,lossPlan).status).toBe('review');
});
for (const width of [1440,390]) test(`Ảnh, dinh dưỡng từng món, nối kế hoạch và lời cổ vũ · ${width}`, async ({page}) => {
 await page.setViewportSize({width,height:900});await page.goto('/');await page.emulateMedia({reducedMotion:'reduce'});
 const chat=page.getByRole('complementary',{name:'Trò chuyện với trợ lý Vi'});
 await chat.getByRole('textbox',{name:'Tin nhắn cho Vi'}).fill('25 tuổi, 65 kg, 170 cm');await chat.getByRole('button',{name:'Gửi tin nhắn'}).click();
 for(const label of ['Nam','Tăng cơ','Tập sức mạnh','Vừa','Xác nhận lịch tập','Đồng ý kế hoạch']) await chat.getByRole('button',{name:label,exact:true}).click();
 await expect(page.getByRole('heading',{name:'Kế hoạch của bạn'})).toBeVisible();
 await page.locator('.suggested-meal').nth(1).scrollIntoViewIfNeeded();
 await expect(page.locator('.suggested-food')).toHaveCount(13);
 await expect(page.locator('.suggested-food .food-photo img').nth(3)).toBeVisible();
 await expect.poll(()=>page.locator('.suggested-food .food-photo img').nth(3).evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBeGreaterThan(0);
 expect(await page.locator('.suggested-food .food-photo').nth(3).evaluate(element=>element.getBoundingClientRect().width)).toBeGreaterThan(200);
 await expect(page.locator('.suggested-meals')).toContainText('Đạm');
 await page.screenshot({path:path.resolve(`../../.impeccable/review/food-plan-${width}.png`)});
 await page.getByRole('button',{name:'Dùng bữa gợi ý này'}).nth(1).click();
 await expect(page.getByRole('button',{name:'Bữa trưa',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(page.getByRole('spinbutton',{name:'Khối lượng Ức gà (g)'})).toHaveValue('150');
 await expect(page.locator('.plan-origin')).toContainText('kế hoạch ngày');
 await expect(page.locator('.meal-alignment')).toContainText('Lựa chọn tốt');
 expect(await page.locator('.ingredient-preview .food-photo').first().evaluate(element=>element.getBoundingClientRect().width)).toBeGreaterThan(300);
 await page.getByRole('spinbutton',{name:'Khối lượng Ức gà (g)'}).fill('');
 await expect(page.locator('.meal-alignment')).toContainText('Cần xác nhận');
 await expect(page.getByRole('button',{name:'Ghi nhận bữa ăn',exact:true})).toBeDisabled();
 await page.getByRole('spinbutton',{name:'Khối lượng Ức gà (g)'}).fill('150');
 await page.locator('.meal-result').scrollIntoViewIfNeeded();await page.screenshot({path:path.resolve(`../../.impeccable/review/food-meal-${width}.png`)});
 await page.getByRole('button',{name:'Ghi nhận bữa ăn',exact:true}).click();
 await expect(chat.locator('.message').filter({hasText:'Đã ghi bữa trưa ngày'})).toHaveCount(1);
 await expect(chat.locator('.message').filter({hasText:'Đã ghi bữa trưa ngày'})).toContainText('Lựa chọn tốt cho kế hoạch tăng cơ');
 await expect(page.getByRole('button',{name:'Đã ghi nhận bữa ăn'})).toBeDisabled();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
