import React from 'react';
import ReactDOM from 'react-dom/client';
import '@fontsource/be-vietnam-pro/vietnamese-400.css';
import '@fontsource/be-vietnam-pro/vietnamese-500.css';
import '@fontsource/be-vietnam-pro/vietnamese-600.css';
import '@fontsource/be-vietnam-pro/vietnamese-700.css';
import '@fontsource/be-vietnam-pro/vietnamese-800.css';
import '@fontsource/be-vietnam-pro/latin-400.css';
import '@fontsource/be-vietnam-pro/latin-500.css';
import '@fontsource/be-vietnam-pro/latin-600.css';
import '@fontsource/be-vietnam-pro/latin-700.css';
import '@fontsource/be-vietnam-pro/latin-800.css';
import App from './App';
import './styles.css';
import './workspace.css';
import './food.css';
import './onboarding.css';
import './mobile.css';
const mobile = window.location.pathname.replace(/\/+$/, '') === '/mobile';
document.documentElement.classList.toggle('mobile-route', mobile);
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App mobile={mobile}/></React.StrictMode>);
