import { useEffect, useId, useRef, useState } from 'react';
import { useJsonState, imagePreview, previewFile } from '../services/storage';
import { Camera, ImagePlus, X } from 'lucide-react';
export function ImagePicker({ body = false, storageKey = body ? 'profile-photo' : 'meal-photo', onChange }: { body?: boolean; storageKey?:string; onChange?: (file?: File) => void }) {
 const [url, setUrl] = useJsonState(storageKey,'',value=>typeof value==='string' && (!value || value.startsWith('data:image/'))); const [error, setError] = useState(''); const id = useId(); const camera = useRef<HTMLInputElement>(null); const library = useRef<HTMLInputElement>(null);
 useEffect(() => { if(url){try{const restored=previewFile(url);onChange?.(restored);}catch{setUrl('');setError('Ảnh lưu chưa đọc được. Hãy chọn ảnh khác.');}} }, []);
 async function choose(next?: File) { if (next && (!['image/jpeg','image/png','image/webp'].includes(next.type) || next.size > 5*1024*1024)) { setError('Chọn ảnh JPEG, PNG hoặc WebP tối đa 5 MB. Bạn vẫn có thể nhập bằng văn bản.'); return; } setError(''); if(!next){setUrl('');onChange?.(undefined);return;}try{const preview=await imagePreview(next);setUrl(preview);onChange?.(next);}catch{setError('Không đọc được ảnh. Chọn ảnh khác hoặc nhập bằng văn bản.');} }
 return <div className="image-picker"><input id={`${id}-camera`} hidden ref={camera} type="file" accept="image/jpeg,image/png,image/webp" capture={body ? 'user' : 'environment'} onChange={e => {choose(e.target.files?.[0]); e.target.value='';}}/><input id={`${id}-library`} hidden ref={library} type="file" accept="image/jpeg,image/png,image/webp" onChange={e => {choose(e.target.files?.[0]); e.target.value='';}}/>{url ? <div className="preview"><img src={url} alt={body ? 'Ảnh cơ thể bạn đã chọn' : 'Ảnh bữa ăn bạn đã chọn'} onError={() => {choose(); setError('Không đọc được ảnh. Chọn ảnh khác hoặc nhập bằng văn bản.');}}/><button className="icon-button remove-image" type="button" aria-label="Xóa ảnh" onClick={() => choose()}><X size={20}/></button></div> : <div className="upload-placeholder"><Camera size={30} strokeWidth={1.5}/><strong>{body ? 'Thêm ảnh cơ thể (tùy chọn)' : 'Bữa ăn của bạn trông thế nào?'}</strong><span>{body ? 'Không cần khuôn mặt hoặc ảnh nhạy cảm.' : 'Ảnh xem trước, chưa được phân tích bằng AI.'}</span></div>}<div className="upload-actions">{!body && <button className="secondary" type="button" onClick={() => camera.current?.click()}><Camera size={18}/>Chụp món ăn</button>}<button className="secondary" type="button" onClick={() => library.current?.click()}><ImagePlus size={18}/>{url ? 'Thay ảnh' : 'Chọn từ thư viện'}</button></div><small>Ảnh xem trước được thu nhỏ và lưu trên thiết bị. JPEG / PNG / WebP · tối đa 5 MB.</small>{error && <p className="error" role="alert">{error}</p>}</div>;
}
