const object = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value);
const finite = (value: unknown) => typeof value === 'number' && Number.isFinite(value);
const strings = (value: unknown) => Array.isArray(value) && value.every(item => typeof item === 'string');
export function validProfile(value: unknown): boolean {
 if (!object(value)) return false;
 return ['age', 'weightKg', 'heightCm'].every(key => finite(value[key])) && ['male', 'female', 'unspecified'].includes(String(value.sex)) && ['maintain', 'gainMuscle', 'loseFat'].includes(String(value.goal)) && typeof value.trainingType === 'string' && typeof value.trainingIntensity === 'string' && Array.isArray(value.weekSchedule) && value.weekSchedule.length === 7 && value.weekSchedule.every((day, i) => object(day) && day.weekday === i + 1 && typeof day.isRestDay === 'boolean' && typeof day.startTime === 'string' && finite(day.durationMinutes));
}
function nutrition(value: unknown): boolean { return object(value) && ['caloriesKcal', 'proteinG', 'carbG', 'fatG'].every(key => finite(value[key]) && Number(value[key]) >= 0); }
function sources(value: unknown): boolean { return Array.isArray(value) && value.every(source => object(source) && typeof source.id === 'string' && typeof source.title === 'string' && ['verified', 'estimated', 'unverified'].includes(String(source.status))); }
function items(value: unknown): boolean { return Array.isArray(value) && value.every(item => object(item) && typeof item.id === 'string' && typeof item.name === 'string' && typeof item.preparation === 'string' && (item.grams === null || finite(item.grams)) && (item.nutrition === null || nutrition(item.nutrition)) && strings(item.sourceIds) && strings(item.missingInfo)); }
export function validSuggestedMeal(value: unknown): boolean { return object(value) && typeof value.name === 'string' && items(value.items) && nutrition(value.total); }
export function validAnalysis(value: unknown): boolean { return object(value) && items(value.items) && nutrition(value.knownTotal) && typeof value.isComplete === 'boolean' && strings(value.assumptions) && strings(value.followUpQuestions) && strings(value.advice) && sources(value.sources) && (value.unmatchedItems === undefined || strings(value.unmatchedItems)); }
export function validPlans(value: unknown): boolean { return Array.isArray(value) && (value.length === 0 || value.length === 7) && value.every((plan, i) => object(plan) && plan.weekday === i + 1 && nutrition(plan.targetMin) && nutrition(plan.targetMax) && Array.isArray(plan.suggestedMeals) && plan.suggestedMeals.every(validSuggestedMeal) && strings(plan.trainingAdvice) && strings(plan.assumptions) && sources(plan.sources)); }
export function validEntries(value: unknown): boolean { return Array.isArray(value) && value.every(entry => object(entry) && typeof entry.id === 'string' && typeof entry.dateKey === 'string' && typeof entry.mealType === 'string' && typeof entry.createdAt === 'string' && validAnalysis(entry.analysis)); }
export function validCheckIns(value: unknown): boolean { return object(value) && Object.values(value).every(day => object(day) && typeof day.nutrition === 'boolean' && typeof day.training === 'boolean' && ['nutritionNote','trainingNote'].every(key => day[key] === undefined || typeof day[key] === 'string' && day[key].length <= 240)); }
